# Generated by Django 2.0 on 2018-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
